#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/akatsuki

PRODUCT_COPY_FILES += \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/color_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/dataflow.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/exposure_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/exposure_ctrl_diagram.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/face_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/flicker_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/food_comp_yummy.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/food_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/fusion_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/fusion_comp.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/fusion_comp_financier.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/fusion_comp_financier.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/fusion_comp_financier_coef.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/fusion_comp_financier_coef.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/fusion_comp_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/fusion_comp_melonpan.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/fusion_comp_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/fusion_comp_raisin.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_bps_gamma16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_bps_gamma16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_fusion_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_fusion_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_abf34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_abf34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_abf34_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_abf34_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_bls12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_bls12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_bpcbcc50.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_bpcbcc50.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_cst12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_cst12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_demosaic36.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_demosaic36.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_gamma16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_gamma16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_linearization33.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_linearization33.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ife_lsc34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ife_lsc34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_anr10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_anr10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_anr10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_anr10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_anr10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_anr10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_anr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_anr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_anr10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_anr10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_cc13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_cc13.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_cst12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_cst12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_cv12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_cv12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_gamma15.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_gamma15.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_ltm13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_ltm13.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_tdl10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_tdl10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_tf10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_tf10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_tf10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_tf10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_tf10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_tf10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_tf10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_tf10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_tf10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_tf10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_sensor_isp_color.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_sensor_isp_color.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_sensor_isp_fsn.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_sensor_isp_fsn.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hal_ctrl_sensor_isp_lin_ne.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hal_ctrl_sensor_isp_lin_ne.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/hdr_comp.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/idt_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_canele.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_cheesescone.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_marble.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_raisin.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/image_conv_spica.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/lens_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/lens_ctrl_common.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/motion_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/motion_detector_sumomo.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/motion_estimation.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/multiframe_nr.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/multiframe_nr_melonpan.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/multiframe_nr_mugichoco.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/multiframe_nr_toppo.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/object_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/object_tracker.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/prc_image_conv.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/process_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/process_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_abf40.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_abf40.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_abf40_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_abf40_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_bls12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_bls12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_demosaic36.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_demosaic36.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_gic30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_gic30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_hnr10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_hnr10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_hnr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_hnr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_linearization34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_linearization34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_bps_pdpc20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_bps_pdpc20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_anr10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_anr10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_anr10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_anr10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_anr10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_anr10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_anr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_anr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_anr10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_anr10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_tf10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_tf10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_tf10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_tf10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_tf10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_tf10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_tf10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_tf10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_tf10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_tf10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/raw_proc_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/raw_proc_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/LGI13BS0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI13BS0/scene_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/color_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/dataflow.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/exposure_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/exposure_ctrl_diagram.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/face_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/flicker_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/food_comp_yummy.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/food_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/fusion_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/fusion_comp.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/fusion_comp_financier.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/fusion_comp_financier.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/fusion_comp_financier_coef.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/fusion_comp_financier_coef.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/fusion_comp_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/fusion_comp_melonpan.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/fusion_comp_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/fusion_comp_raisin.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_bps_gamma16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_bps_gamma16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_fusion_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_fusion_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_abf34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_abf34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_abf34_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_abf34_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_bls12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_bls12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_bpcbcc50.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_bpcbcc50.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_cst12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_cst12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_demosaic36.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_demosaic36.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_gamma16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_gamma16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_linearization33.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_linearization33.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ife_lsc34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ife_lsc34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_anr10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_anr10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_anr10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_anr10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_anr10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_anr10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_anr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_anr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_anr10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_anr10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_cc13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_cc13.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_cst12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_cst12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_cv12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_cv12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_gamma15.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_gamma15.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_ltm13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_ltm13.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_tdl10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_tdl10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_tf10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_tf10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_tf10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_tf10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_tf10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_tf10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_tf10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_tf10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_tf10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_tf10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_sensor_isp_color.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_sensor_isp_color.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_sensor_isp_fsn.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_sensor_isp_fsn.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hal_ctrl_sensor_isp_lin_ne.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hal_ctrl_sensor_isp_lin_ne.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/hdr_comp.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/idt_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_canele.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_cheesescone.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_marble.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_raisin.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/image_conv_spica.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/lens_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/lens_ctrl_common.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/motion_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/motion_detector_sumomo.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/motion_estimation.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/multiframe_nr.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/multiframe_nr_melonpan.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/multiframe_nr_mugichoco.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/multiframe_nr_toppo.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/object_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/object_tracker.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/prc_image_conv.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/process_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/process_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_abf40.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_abf40.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_abf40_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_abf40_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_bls12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_bls12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_demosaic36.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_demosaic36.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_gic30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_gic30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_hnr10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_hnr10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_hnr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_hnr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_linearization34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_linearization34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_bps_pdpc20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_bps_pdpc20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_anr10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_anr10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_anr10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_anr10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_anr10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_anr10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_anr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_anr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_anr10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_anr10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_tf10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_tf10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_tf10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_tf10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_tf10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_tf10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_tf10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_tf10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_tf10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_tf10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/raw_proc_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/raw_proc_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/MTM13BS0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MTM13BS0/scene_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/color_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/dataflow.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/exposure_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/exposure_ctrl_diagram.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/face_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/flicker_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/food_comp_yummy.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/food_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/food_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/fusion_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/fusion_comp.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/fusion_comp_financier.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/fusion_comp_financier.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/fusion_comp_financier_coef.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/fusion_comp_financier_coef.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/fusion_comp_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/fusion_comp_melonpan.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/fusion_comp_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/fusion_comp_raisin.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_bps_gamma16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_bps_gamma16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_fusion_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_fusion_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_abf34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_abf34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_abf34_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_abf34_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_bls12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_bls12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_bpcbcc50.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_bpcbcc50.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_cst12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_cst12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_demosaic36.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_demosaic36.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_gamma16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_gamma16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_linearization33.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_linearization33.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ife_lsc34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ife_lsc34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_anr10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_anr10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_anr10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_anr10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_anr10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_anr10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_anr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_anr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_anr10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_anr10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_cc13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_cc13.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_cst12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_cst12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_cv12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_cv12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_gamma15.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_gamma15.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_ltm13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_ltm13.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_tdl10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_tdl10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_tf10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_tf10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_tf10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_tf10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_tf10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_tf10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_tf10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_tf10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_tf10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_tf10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_sensor_isp_color.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_sensor_isp_color.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_sensor_isp_fsn.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_sensor_isp_fsn.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hal_ctrl_sensor_isp_lin_ne.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hal_ctrl_sensor_isp_lin_ne.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/hdr_comp.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/idt_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_canele.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_canele.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_cheesescone.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_marble.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_raisin.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/image_conv_spica.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/image_conv_spica.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/lens_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/lens_ctrl_common.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/motion_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/motion_detector_sumomo.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/motion_estimation.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/multiframe_nr_melonpan.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr_melonpan.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/multiframe_nr_mugichoco.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr_mugichoco.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/multiframe_nr_toppo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/multiframe_nr_toppo.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/object_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/object_tracker.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/prc_image_conv.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/process_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/process_ctrl.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_abf40.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_abf40.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_abf40_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_abf40_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_bls12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_bls12.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_demosaic36.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_demosaic36.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_gic30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_gic30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_hnr10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_hnr10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_hnr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_hnr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_linearization34.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_linearization34.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_bps_pdpc20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_bps_pdpc20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_anr10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_anr10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_anr10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_anr10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_anr10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_anr10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_anr10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_anr10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_anr10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_anr10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_asf30.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_asf30.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_cs20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_cs20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_gra10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_gra10.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_tf10_dc04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_tf10_dc04.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_tf10_dc16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_tf10_dc16.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_tf10_dc64.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_tf10_dc64.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_tf10_disable.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_tf10_disable.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_tf10_full.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_tf10_full.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_ipe_upscale20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_ipe_upscale20.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/raw_proc_platform_nree.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/raw_proc_platform_nree.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2/scene_detector.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2_BU64747GWZ_XCF.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2_BU64747GWZ_XCF.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/SOI20BS2_BU64747GWZ_XFW.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI20BS2_BU64747GWZ_XFW.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/akatsuki/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/akatsuki/proprietary/vendor/etc/acdbdata/Sony_tama_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Handset_cal.acdb \
    vendor/sony/akatsuki/proprietary/vendor/etc/acdbdata/Sony_tama_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_tama_Speaker_cal.acdb \
    vendor/sony/akatsuki/proprietary/vendor/etc/change.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/change.cfg \
    vendor/sony/akatsuki/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/sony/akatsuki/proprietary/vendor/etc/qdcm_calib_data_5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_5.xml \
    vendor/sony/akatsuki/proprietary/vendor/etc/sensors/registry/config/sdm845_ak991x_0_somc_product.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_ak991x_0_somc_product.json \
    vendor/sony/akatsuki/proprietary/vendor/etc/sensors/registry/config/sdm845_lsm6dsm_0_somc_product.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_lsm6dsm_0_somc_product.json \
    vendor/sony/akatsuki/proprietary/vendor/etc/sensors/registry/registry/sensors_registry:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_registry \
    vendor/sony/akatsuki/proprietary/vendor/etc/sensors/registry/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/sns_reg_config \
    vendor/sony/akatsuki/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/sony/akatsuki/proprietary/vendor/etc/wifi/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.bin \
    vendor/sony/akatsuki/proprietary/vendor/firmware/fpctzfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.b01 \
    vendor/sony/akatsuki/proprietary/vendor/firmware/fpctzfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzfingerprint.mdt \
    vendor/sony/akatsuki/proprietary/vendor/firmware/touch_module_id_0x01.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x01.img \
    vendor/sony/akatsuki/proprietary/vendor/lib/camera/com.sony.sensormodule.blakiston_imx400.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.sony.sensormodule.blakiston_imx400.bin \
    vendor/sony/akatsuki/proprietary/vendor/lib/camera/com.sony.sensormodule.poodle_imx258.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.sony.sensormodule.poodle_imx258.bin \
    vendor/sony/akatsuki/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/sony/akatsuki/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/sony/akatsuki/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/sony/akatsuki/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    android.hardware.bluetooth@1.0-impl-qti \
    vendor.qti.gnss@3.0-impl \
    libacdbloader \
    libbtnv \
    libcammw_util \
    libdataitems \
    libexcal_core \
    libkeymasterutils \
    liblbs_core \
    libloc_api_v02 \
    liblocationservice \
    liblocationservice_glue \
    libslimclient \
    libsomc_camerapal \
    sensors.ssc \
    libexcal_face_detector_plugin \
    libexcal_hal_ctrl_plugin \
    libexcal_image_conv_plugin \
    libexcal_jpeg_enc_plugin \
    libexcal_lens_ctrl_plugin \
    libexcal_raw_proc_plugin \
    libcacao_process_ctrl \
    libcammw \
    libexcal_system \
    libsomc_chokoballpal \
    android.hardware.keymaster@4.0-service-qti \
    vendor.semc.hardware.secd@1.0-service \
    slim_daemon
